### ISSUE TITLE
Add upload call for NyaaPantsu

### ISSUE THREAD

**Issue by JuanjoSalvador** [JuanjoSalvador/NyaaPy#26]
**To Do**

Add an upload function to upload torrent's info. Based on `upload` method on NyaaPantsu API.

**Check**

[NyaaPantsu API docs](https://nyaa.pantsu.cat/apidoc)

**Comment by heroas** [comment]
Hello! Saw you added an hackoberfest label recently.
I've been working with your module fairly intimately for a personal project of mine.
I would love to help out, Is this a good feature to start?

**Comment by JuanjoSalvador** [comment]
Hi @heroas!

I've been reading others "begineer-friendly" issues on Github, but most of them are something like "Pull Request tutorial", and I don't like those things. NyaaPy is a side project, but it is important for me (and another side project). I think adding new WIP/planned functions to the module would be a good starting point to contribute with "serious things".

So, let's do this. Feel free to ask everything you need, and let the code start!

(in a nutshell: yes, is a good feature to start)

**Comment by JuanjoSalvador** [comment]
Btw @heroas if you can do the upload call, the update call is pretty easy too.

I will write a contributors guide tomorrow night.

**Comment by heroas** [comment]
Awesome! Thank you for the opportunity! I'll see to both!

**Comment by JuanjoSalvador** [comment]
Here is the guide:

https://github.com/JuanjoSalvador/NyaaPy/blob/master/HOW-TO-CONTRIBUTE.md

Happy coding!
