### ISSUE TITLE
Error on code ```Utils.py```

### ISSUE THREAD

**Issue by zerasul** [JuanjoSalvador/NyaaPy#39]
There is an error on line 79:

https://github.com/JuanjoSalvador/NyaaPy/blob/b89de78f76ffc5db29ebcdd9fcaf0dc28a022345/NyaaPy/utils.py#L79

**Comment by zerasul** [comment]
I'll send you a PR later.

**Comment by JuanjoSalvador** [comment]
Yep, fixed. Thanks.
