### ISSUE TITLE
Update Pantsu data

### ISSUE THREAD

**Issue by JuanjoSalvador** [JuanjoSalvador/NyaaPy#53]
Since nyaa.pantsu.cat has been moved to nyaa.net, we need to update our endpoints.

**Comment by Euklios** [comment]
Is this issue still relevant?
As far as I understand, pantsu has been replaced by sukebei.
Seams to be backed by: https://www.reddit.com/r/animepiracy/comments/on9azy

**Comment by JuanjoSalvador** [comment]
At this point, I think not.
