### ISSUE TITLE
No matching distribution found for nyaapy==0.6.2

### ISSUE THREAD

**Issue by twig** [JuanjoSalvador/NyaaPy#57]
```
pip._internal.exceptions.DistributionNotFound: No matching distribution found for nyaapy==0.6.2
```

when using pip from Windows on Python 3.8.

**Comment by twig** [comment]
Not pinning v0.6.2 results in 0.6.1 being installed

**Comment by JuanjoSalvador** [comment]
Seems like I forgot to upgrade PyPi.

https://pypi.org/project/nyaapy/

**Comment by twig** [comment]
lol any idea how long it'll take to push the current version out?

or how to add the github version to `requests.txt`?

**Comment by JuanjoSalvador** [comment]
Actually the project is quite abandoned now. You can manually install the master version by cloning the repo and using 

```
python setup.py install
```

But I will upgrade it as soon as possible.

**Comment by Euklios** [comment]
@twig 
@twig 
pip allows installing from a git-repository using the following command.
`pip install git+https://github.com/JuanjoSalvador/NyaaPy.git`; this also works within `requirements.txt` by adding the line `git+https://github.com/JuanjoSalvador/NyaaPy.git`.

I haven't tried using this specific repository, but it should work as a temporary workaround for you.

**Comment by JuanjoSalvador** [comment]
Already updated. Sorry for my lapsus about this one. New release includes other minor fixes and improvements. I think this could be even a RC for v0.7

**Comment by twig** [comment]
That's what I ended up doing @Euklios

Thanks @JuanjoSalvador !
